spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5442/dev_customer_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: postgres
      mode: never
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
