spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9001/realms/ticketing-security-realm


keycloak:
  auth:
    jwk-set-uri: http://localhost:9001/realms/ticketing-security-realm/protocol/openid-connect/certs
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      orders-circuit-breaker:
        baseConfig: default
      bookings-circuit-breaker:
        baseConfig: default
      inventory-circuit-breaker:
        baseConfig: default
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0]:
      name: Inventory Service
      url: /docs/inventoryservice/v3/api-docs
    urls[1]:
      name: Booking Service
      url: /docs/bookingsservice/v3/api-docs
  api-docs:
    path: /v3/api-docs

